// Dictionary strings for Bahasa Indonesia & English support

export type Language = 'id' | 'en';

export const DICTIONARY = {
  id: {
    nav: {
      home: 'Beranda',
      fontStyles: 'Gaya Font',
      platforms: 'Platform',
      games: 'Game Nickname',
      symbols: 'Simbol & Kaomoji',
      blog: 'Artikel / Blog',
      generateBtn: 'Buat Font',
    },
    hero: {
      titlePrefix: 'Tulisan Aesthetic',
      titleSuffix: 'Generator Teks Keren',
      subtitle: 'Konversi teks biasa menjadi font Unicode aesthetic keren untuk Instagram, TikTok, WhatsApp & Game Nickname secara instan dan 100% gratis.',
      placeholder: 'Tulis teks di sini... (contoh: Tulisan Aesthetic)',
      btnGenerate: 'Generate Font',
      btnCopyAll: 'Salin Semua',
      btnRandom: 'Gaya Acak',
      btnClear: 'Hapus Teks',
      filterAll: 'Semua Gaya',
      filterTrending: '🔥 Trending',
      filterGaming: '🎮 Gaming',
      filterCute: '🌸 Cute',
      filterGothic: '⚔️ Gothic',
      copySuccess: 'Teks berhasil disalin ke clipboard!',
    },
    popular: {
      tag: 'Gaya Terfavorit',
      title: 'Pilihan Font Styles Populer',
      subtitle: 'Pilih gaya font Unicode terbaik yang paling sering digunakan oleh content creator & gamer.',
      tryBtn: 'Salin Style Ini',
    },
    platforms: {
      tag: 'Kompatibilitas 100%',
      title: 'Dukungan Semua Platform Media Sosial',
      subtitle: 'Font Unicode kami dirancang agar dapat terbaca sempurna tanpa ubah ke kotak-kotak.',
      igDesc: 'Optimal untuk Bio Instagram, Caption aesthetic, dan Story highlight.',
      ttDesc: 'Tampil menonjol di Bio TikTok, komentar, dan video description.',
      waDesc: 'Percantik Info WhatsApp, status teks, dan pesan obrolan grup.',
      dcDesc: 'Nama server Discord, role name, dan chat status aesthetic.',
      fbDesc: 'Status Facebook, nama akun aesthetic, dan postingan grup.',
      twDesc: 'Display name Twitter / X, tweet aesthetic, dan header bio.',
    },
    games: {
      tag: 'Nick Generator Pro',
      title: 'Gaming Nickname Aesthetic',
      subtitle: 'Buat nama akun game Free Fire, PUBG, MLBB & Valorant terlihat seperti pro player esports.',
      copyNick: 'Salin Nickname',
    },
    symbols: {
      tag: 'Ribuan Simbol Aesthetic',
      title: 'Koleksi Simbol, Emoji & Kaomoji',
      subtitle: 'Klik simbol atau emoticon teks di bawah untuk menyalin langsung ke clipboard.',
      viewAll: 'Buka Katalog Simbol Lengkap',
    },
    whyUs: {
      tag: 'Keunggulan Kami',
      title: 'Mengapa Memilih Tulisan Aesthetic?',
      subtitle: 'Platform generator font Unicode tercanggih, tercepat, dan paling aman di Indonesia.',
      f1Title: '⚡ Proses Kilat (<10ms)',
      f1Desc: 'Teks langsung terkonversi secara otomatis begitu Anda mengetik tanpa perlu reload.',
      f2Title: '📱 Support Semua Perangkat',
      f2Desc: 'Kompatibel 100% dengan iOS, Android, Windows, Mac, dan Linux tanpa aplikasi tambahan.',
      f3Title: '🎨 100+ Variasi Font',
      f3Desc: 'Koleksi Unicode terlengkap mulai dari Small Caps, Gothic, Bubble, hingga Zalgo Glitch.',
      f4Title: '🆓 100% Gratis Selamanya',
      f4Desc: 'Gunakan tanpa batas, tanpa registrasi akun, tanpa iklan yang mengganggu.',
    },
    stats: {
      genCount: '5M+',
      genLabel: 'Teks Dihasilkan',
      stylesCount: '120+',
      stylesLabel: 'Gaya Font Unicode',
      usersCount: '50K+',
      usersLabel: 'Pengguna Aktif Harian',
      compatCount: '99.9%',
      compatLabel: 'Kompatibilitas Perangkat',
    },
    blog: {
      tag: 'Edukasi & Tips',
      title: 'Artikel & Panduan Terbaru',
      subtitle: 'Tips memaksimalkan bio media sosial, tips nickname game, dan fakta seputar Unicode.',
      readMore: 'Baca Selengkapnya',
    },
    faq: {
      tag: 'Pertanyaan Umum',
      title: 'Pertanyaan yang Sering Diajukan (FAQ)',
      subtitle: 'Temukan jawaban lengkap seputar penggunaan font aesthetic dan simbol Unicode.',
    },
    cta: {
      title: 'Mulai Buat Tulisan Aesthetic Keren Sekarang!',
      subtitle: 'Ubah teks biasa Anda dalam hitungan detik. Gratis dan tanpa perlu download aplikasi apapun.',
      btnText: 'Buat Font Sekarang',
    },
    footer: {
      about: 'Tulisan Aesthetic adalah platform generator font Unicode AI terdepan di Indonesia yang membantu content creator, gamer, dan pelajar membuat teks estetik secara instan.',
      quickLinks: 'Navigasi Cepat',
      legal: 'Hukum & Ketentuan',
      privacy: 'Kebijakan Privasi',
      terms: 'Syarat & Ketentuan',
      disclaimer: 'Penafian (Disclaimer)',
      contact: 'Hubungi Kami',
      rights: 'Hak Cipta Dilindungi Undang-Undang.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      fontStyles: 'Font Styles',
      platforms: 'Platforms',
      games: 'Game Nicknames',
      symbols: 'Symbols & Kaomoji',
      blog: 'Blog & Articles',
      generateBtn: 'Generate Fonts',
    },
    hero: {
      titlePrefix: 'Aesthetic Text',
      titleSuffix: 'Unicode Generator',
      subtitle: 'Convert normal text into aesthetic Unicode fonts for Instagram, TikTok, WhatsApp & Gaming Nicknames instantly.',
      placeholder: 'Type your text here... (e.g. Aesthetic Fonts)',
      btnGenerate: 'Generate Text',
      btnCopyAll: 'Copy All',
      btnRandom: 'Random Style',
      btnClear: 'Clear Text',
      filterAll: 'All Styles',
      filterTrending: '🔥 Trending',
      filterGaming: '🎮 Gaming',
      filterCute: '🌸 Cute',
      filterGothic: '⚔️ Gothic',
      copySuccess: 'Text copied to clipboard!',
    },
    popular: {
      tag: 'Most Popular',
      title: 'Popular Aesthetic Font Styles',
      subtitle: 'Handpicked Unicode fonts loved by social media creators and gamers worldwide.',
      tryBtn: 'Copy This Style',
    },
    platforms: {
      tag: '100% Compatible',
      title: 'Cross-Platform Social Media Support',
      subtitle: 'Our Unicode fonts are tested to display clearly across all major social networks.',
      igDesc: 'Ideal for Instagram Bio, aesthetic captions, and story highlights.',
      ttDesc: 'Stand out on TikTok bios, video descriptions, and comments.',
      waDesc: 'Elevate your WhatsApp Info, text status, and group chats.',
      dcDesc: 'Discord server names, custom role titles, and aesthetic statuses.',
      fbDesc: 'Facebook statuses, stylized profile names, and group posts.',
      twDesc: 'Twitter / X display name, aesthetic tweets, and profile bio header.',
    },
    games: {
      tag: 'Nick Generator Pro',
      title: 'Aesthetic Gaming Nicknames',
      subtitle: 'Create pro player names for Free Fire, PUBG, MLBB & Valorant in seconds.',
      copyNick: 'Copy Nickname',
    },
    symbols: {
      tag: 'Thousands of Symbols',
      title: 'Aesthetic Symbols, Emojis & Kaomoji',
      subtitle: 'Click any symbol or text emoticon to copy directly to your clipboard.',
      viewAll: 'Open Complete Symbol Catalog',
    },
    whyUs: {
      tag: 'Why Choose Us',
      title: 'Why Tulisan Aesthetic?',
      subtitle: 'Indonesia’s most advanced, ultra-fast, and secure Unicode generator platform.',
      f1Title: '⚡ Ultra-Fast (<10ms)',
      f1Desc: 'Instant text conversion as you type without needing page reloads.',
      f2Title: '📱 Multi-Device Compatible',
      f2Desc: 'Works seamlessly on iOS, Android, Windows, macOS, and Linux.',
      f3Title: '🎨 100+ Font Styles',
      f3Desc: 'Vast Unicode font library from Small Caps, Gothic, Bubble, to Glitch Zalgo.',
      f4Title: '🆓 100% Free Forever',
      f4Desc: 'Unlimited usage, no sign-ups required, zero intrusive popup ads.',
    },
    stats: {
      genCount: '5M+',
      genLabel: 'Texts Generated',
      stylesCount: '120+',
      stylesLabel: 'Unicode Styles',
      usersCount: '50K+',
      usersLabel: 'Daily Active Users',
      compatCount: '99.9%',
      compatLabel: 'Platform Compatibility',
    },
    blog: {
      tag: 'Education & Tips',
      title: 'Latest Articles & Guides',
      subtitle: 'Tips for optimizing social media bios, gaming name tricks, and Unicode insights.',
      readMore: 'Read Article',
    },
    faq: {
      tag: 'FAQ',
      title: 'Frequently Asked Questions',
      subtitle: 'Everything you need to know about using aesthetic text and Unicode symbols.',
    },
    cta: {
      title: 'Start Generating Aesthetic Text Today!',
      subtitle: 'Transform plain text in seconds. 100% free, no app downloads required.',
      btnText: 'Generate Fonts Now',
    },
    footer: {
      about: 'Tulisan Aesthetic is the premier AI-powered Unicode text generator platform, helping creators and gamers craft beautiful typography instantly.',
      quickLinks: 'Quick Links',
      legal: 'Legal & Policy',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      disclaimer: 'Disclaimer',
      contact: 'Contact Us',
      rights: 'All Rights Reserved.',
    },
  },
};
