export interface EmojiSymbolItem {
  symbol: string;
  name: string;
  category: 'Smileys & Emotion' | 'People & Body' | 'Animals & Nature' | 'Food & Drink' | 'Travel & Places' | 'Activities' | 'Objects' | 'Symbols' | 'Flags';
  collections?: string[];
}

export const EMOJI_CATEGORIES_LIST = [
  'All Emojis',
  'Smileys & Emotion',
  'People & Body',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols',
  'Flags',
] as const;

export const EMOJI_COLLECTIONS_LIST = [
  { id: 'love', name: 'Love ❤️', desc: 'Ekspresi cinta, hati, & keromantisan', items: ['❤️', '💖', '💕', '🥰', '😍', '💌', '💓', '💗'] },
  { id: 'happy', name: 'Happy 😀', desc: 'Ekspresi kegembiraan & tawa gembira', items: ['😀', '😃', '😄', '😁', '🥳', '✨', '🤩', '😆'] },
  { id: 'sad', name: 'Sad 🥺', desc: 'Ekspresi sedih, haru, & empati', items: ['🥺', '😭', '😢', '💔', '😔', '😿', '🌧️', '🤧'] },
  { id: 'fire', name: 'Fire 🔥', desc: 'Elemen semangat, tren viral, & panas', items: ['🔥', '⚡', '💥', '🌶️', '🚀', '💯', '✨', '🌟'] },
  { id: 'stars', name: 'Stars ✨', desc: 'Bintang berkilau, keajaiban, & luar angkasa', items: ['✨', '⭐', '🌟', '💫', '🌠', '🌌', '🌃', '✴️'] },
  { id: 'hearts', name: 'Hearts 💖', desc: 'Koleksi lengkap emoji warna-warni hati', items: ['❤️', '🧡', '💛', '💚', '💙', '💜', '🤎', '🤍'] },
  { id: 'gaming', name: 'Gaming 🎮', desc: 'Ikon game, pro player, & hiburan digital', items: ['🎮', '🕹️', '👾', '🎧', '🏆', '🎯', '👑', '🥇'] },
  { id: 'celebration', name: 'Celebration 🥳', desc: 'Pesta ulang tahun, kelulusan, & festival', items: ['🥳', '🎉', '🎊', '🎁', '🎂', '🍾', '🎟️', '🎈'] },
  { id: 'weather', name: 'Weather ☀️', desc: 'Cuaca, musim, matahari, & alam bebas', items: ['☀️', '🌙', '☁️', '❄️', '🌈', '🌧️', '🌩️', '🌊'] },
  { id: 'animals', name: 'Animals 🐶', desc: 'Hewan peliharaan imut & alam liar', items: ['🐶', '🐱', '🐰', '🦊', '🐻', '🐼', '🦁', '🦄'] },
];

export const EMOJI_SYMBOLS_DATA: EmojiSymbolItem[] = [
  // 1. Smileys & Emotion
  { symbol: '😀', name: 'Grinning Face', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😆', name: 'Grinning Squinting Face', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😅', name: 'Grinning Face with Sweat', category: 'Smileys & Emotion' },
  { symbol: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😂', name: 'Face with Tears of Joy', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '🙂', name: 'Slightly Smiling Face', category: 'Smileys & Emotion' },
  { symbol: '🙃', name: 'Upside-Down Face', category: 'Smileys & Emotion' },
  { symbol: '😉', name: 'Winking Face', category: 'Smileys & Emotion' },
  { symbol: '😊', name: 'Smiling Face with Smiling Eyes', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '😇', name: 'Smiling Face with Halo', category: 'Smileys & Emotion' },
  { symbol: '🥰', name: 'Smiling Face with Hearts', category: 'Smileys & Emotion', collections: ['love', 'happy'] },
  { symbol: '😍', name: 'Smiling Face with Heart-Eyes', category: 'Smileys & Emotion', collections: ['love'] },
  { symbol: '🤩', name: 'Star-Struck Face', category: 'Smileys & Emotion', collections: ['stars', 'happy'] },
  { symbol: '😘', name: 'Face Blowing a Kiss', category: 'Smileys & Emotion', collections: ['love'] },
  { symbol: '😗', name: 'Kissing Face', category: 'Smileys & Emotion' },
  { symbol: '😚', name: 'Kissing Face with Closed Eyes', category: 'Smileys & Emotion' },
  { symbol: '😙', name: 'Kissing Face with Smiling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😋', name: 'Face Savoring Food', category: 'Smileys & Emotion' },
  { symbol: '😛', name: 'Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '😜', name: 'Winking Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '🤪', name: 'Zany Face', category: 'Smileys & Emotion' },
  { symbol: '😝', name: 'Squinting Face with Tongue', category: 'Smileys & Emotion' },
  { symbol: '🤑', name: 'Money-Mouth Face', category: 'Smileys & Emotion' },
  { symbol: '🤗', name: 'Hugging Face', category: 'Smileys & Emotion' },
  { symbol: '🤭', name: 'Face with Hand Over Mouth', category: 'Smileys & Emotion' },
  { symbol: '🤫', name: 'Shushing Face', category: 'Smileys & Emotion' },
  { symbol: '🤔', name: 'Thinking Face', category: 'Smileys & Emotion' },
  { symbol: '🤐', name: 'Zipper-Mouth Face', category: 'Smileys & Emotion' },
  { symbol: '🤨', name: 'Face with Raised Eyebrow', category: 'Smileys & Emotion' },
  { symbol: '😐', name: 'Neutral Face', category: 'Smileys & Emotion' },
  { symbol: '😑', name: 'Expressionless Face', category: 'Smileys & Emotion' },
  { symbol: '😶', name: 'Face Without Mouth', category: 'Smileys & Emotion' },
  { symbol: '😏', name: 'Smirking Face', category: 'Smileys & Emotion' },
  { symbol: '😒', name: 'Unamused Face', category: 'Smileys & Emotion' },
  { symbol: '🙄', name: 'Face with Rolling Eyes', category: 'Smileys & Emotion' },
  { symbol: '😬', name: 'Grimacing Face', category: 'Smileys & Emotion' },
  { symbol: '🤥', name: 'Lying Face', category: 'Smileys & Emotion' },
  { symbol: '😌', name: 'Relieved Face', category: 'Smileys & Emotion' },
  { symbol: '😔', name: 'Pensive Face', category: 'Smileys & Emotion', collections: ['sad'] },
  { symbol: '😪', name: 'Sleepy Face', category: 'Smileys & Emotion' },
  { symbol: '🤤', name: 'Drooling Face', category: 'Smileys & Emotion' },
  { symbol: '😴', name: 'Sleeping Face', category: 'Smileys & Emotion' },
  { symbol: '😷', name: 'Face with Medical Mask', category: 'Smileys & Emotion' },
  { symbol: '🤒', name: 'Face with Thermometer', category: 'Smileys & Emotion' },
  { symbol: '🤕', name: 'Face with Head-Bandage', category: 'Smileys & Emotion' },
  { symbol: '🤢', name: 'Nauseated Face', category: 'Smileys & Emotion' },
  { symbol: '🤮', name: 'Face Vomiting', category: 'Smileys & Emotion' },
  { symbol: '🤧', name: 'Sneezing Face', category: 'Smileys & Emotion', collections: ['sad'] },
  { symbol: '🥵', name: 'Hot Face', category: 'Smileys & Emotion', collections: ['fire'] },
  { symbol: '🥶', name: 'Cold Face', category: 'Smileys & Emotion', collections: ['weather'] },
  { symbol: '🥴', name: 'Woozy Face', category: 'Smileys & Emotion' },
  { symbol: '😵', name: 'Dizzy Face', category: 'Smileys & Emotion' },
  { symbol: '🤯', name: 'Exploding Head', category: 'Smileys & Emotion', collections: ['fire'] },
  { symbol: '🤠', name: 'Cowboy Hat Face', category: 'Smileys & Emotion' },
  { symbol: '🥳', name: 'Partying Face', category: 'Smileys & Emotion', collections: ['celebration', 'happy'] },
  { symbol: '😎', name: 'Smiling Face with Sunglasses', category: 'Smileys & Emotion', collections: ['happy'] },
  { symbol: '🤓', name: 'Nerd Face', category: 'Smileys & Emotion' },
  { symbol: '🧐', name: 'Face with Monocle', category: 'Smileys & Emotion' },
  { symbol: '😕', name: 'Confused Face', category: 'Smileys & Emotion' },
  { symbol: '😟', name: 'Worried Face', category: 'Smileys & Emotion' },
  { symbol: '🙁', name: 'Slightly Frowning Face', category: 'Smileys & Emotion' },
  { symbol: '😮', name: 'Face with Open Mouth', category: 'Smileys & Emotion' },
  { symbol: '😯', name: 'Hushed Face', category: 'Smileys & Emotion' },
  { symbol: '😲', name: 'Astonished Face', category: 'Smileys & Emotion' },
  { symbol: '😳', name: 'Flushed Face', category: 'Smileys & Emotion' },
  { symbol: '🥺', name: 'Pleading Face', category: 'Smileys & Emotion', collections: ['sad'] },
  { symbol: '😦', name: 'Frowning Face with Open Mouth', category: 'Smileys & Emotion' },
  { symbol: '😧', name: 'Anguished Face', category: 'Smileys & Emotion' },
  { symbol: '😨', name: 'Fearful Face', category: 'Smileys & Emotion' },
  { symbol: '😰', name: 'Anxious Face with Sweat', category: 'Smileys & Emotion' },
  { symbol: '😥', name: 'Sad but Relieved Face', category: 'Smileys & Emotion', collections: ['sad'] },
  { symbol: '😢', name: 'Crying Face', category: 'Smileys & Emotion', collections: ['sad'] },
  { symbol: '😭', name: 'Loudly Crying Face', category: 'Smileys & Emotion', collections: ['sad'] },

  // 2. People & Body
  { symbol: '👋', name: 'Waving Hand', category: 'People & Body' },
  { symbol: '🤚', name: 'Raised Back of Hand', category: 'People & Body' },
  { symbol: '🖐️', name: 'Hand with Fingers Splayed', category: 'People & Body' },
  { symbol: '✋', name: 'Raised Hand', category: 'People & Body' },
  { symbol: '🖖', name: 'Vulcan Salute', category: 'People & Body' },
  { symbol: '👌', name: 'OK Hand', category: 'People & Body' },
  { symbol: '🤌', name: 'Pinched Fingers', category: 'People & Body' },
  { symbol: '🤏', name: 'Pinching Hand', category: 'People & Body' },
  { symbol: '✌️', name: 'Victory Hand', category: 'People & Body' },
  { symbol: '🤞', name: 'Crossed Fingers', category: 'People & Body' },
  { symbol: '🤟', name: 'Love-You Gesture', category: 'People & Body', collections: ['love'] },
  { symbol: '🤘', name: 'Sign of the Horns', category: 'People & Body' },
  { symbol: '🤙', name: 'Call Me Hand', category: 'People & Body' },
  { symbol: '👈', name: 'Backhand Index Pointing Left', category: 'People & Body' },
  { symbol: '👉', name: 'Backhand Index Pointing Right', category: 'People & Body' },
  { symbol: '👆', name: 'Backhand Index Pointing Up', category: 'People & Body' },
  { symbol: '🖕', name: 'Middle Finger', category: 'People & Body' },
  { symbol: '👇', name: 'Backhand Index Pointing Down', category: 'People & Body' },
  { symbol: '☝️', name: 'Index Pointing Up', category: 'People & Body' },
  { symbol: '👍', name: 'Thumbs Up', category: 'People & Body' },
  { symbol: '👎', name: 'Thumbs Down', category: 'People & Body' },
  { symbol: '✊', name: 'Raised Fist', category: 'People & Body' },
  { symbol: '👊', name: 'Oncoming Fist', category: 'People & Body' },
  { symbol: '🤛', name: 'Left-Facing Fist', category: 'People & Body' },
  { symbol: '🤜', name: 'Right-Facing Fist', category: 'People & Body' },
  { symbol: '👏', name: 'Clapping Hands', category: 'People & Body', collections: ['celebration'] },
  { symbol: '🙌', name: 'Raising Hands', category: 'People & Body', collections: ['celebration'] },
  { symbol: '👐', name: 'Open Hands', category: 'People & Body' },
  { symbol: '🤲', name: 'Palms Up Together', category: 'People & Body' },
  { symbol: '🤝', name: 'Handshake', category: 'People & Body' },
  { symbol: '🙏', name: 'Folded Hands Pray', category: 'People & Body' },
  { symbol: '✍️', name: 'Writing Hand', category: 'People & Body' },
  { symbol: '💅', name: 'Nail Polish', category: 'People & Body' },
  { symbol: '🤳', name: 'Selfie', category: 'People & Body' },
  { symbol: '💪', name: 'Flexed Biceps Muscle', category: 'People & Body', collections: ['fire'] },
  { symbol: '🧠', name: 'Brain', category: 'People & Body' },
  { symbol: '🫀', name: 'Anatomical Heart', category: 'People & Body' },
  { symbol: '🫁', name: 'Lungs', category: 'People & Body' },
  { symbol: '🦷', name: 'Tooth', category: 'People & Body' },
  { symbol: '🦴', name: 'Bone', category: 'People & Body' },
  { symbol: '👀', name: 'Eyes', category: 'People & Body' },
  { symbol: '👁️', name: 'Eye', category: 'People & Body' },
  { symbol: '👅', name: 'Tongue', category: 'People & Body' },
  { symbol: '👄', name: 'Mouth Lips', category: 'People & Body', collections: ['love'] },

  // 3. Animals & Nature
  { symbol: '🐶', name: 'Dog Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐱', name: 'Cat Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐭', name: 'Mouse Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐹', name: 'Hamster Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐰', name: 'Rabbit Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦊', name: 'Fox Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐻', name: 'Bear Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐼', name: 'Panda Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐻‍❄️', name: 'Polar Bear', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐨', name: 'Koala', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐯', name: 'Tiger Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦁', name: 'Lion Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐮', name: 'Cow Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐷', name: 'Pig Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐸', name: 'Frog Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐵', name: 'Monkey Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🙈', name: 'See-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🙉', name: 'Hear-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🙊', name: 'Speak-No-Evil Monkey', category: 'Animals & Nature' },
  { symbol: '🐔', name: 'Chicken', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐧', name: 'Penguin', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐦', name: 'Bird', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐤', name: 'Baby Chick', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦆', name: 'Duck', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦅', name: 'Eagle', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦉', name: 'Owl', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦇', name: 'Bat', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐺', name: 'Wolf', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐗', name: 'Boar', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐴', name: 'Horse Face', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦄', name: 'Unicorn', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐝', name: 'Honeybee', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐛', name: 'Bug Caterpillar', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🦋', name: 'Butterfly', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐌', name: 'Snail', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐞', name: 'Lady Beetle', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🐜', name: 'Ant', category: 'Animals & Nature', collections: ['animals'] },
  { symbol: '🌸', name: 'Cherry Blossom', category: 'Animals & Nature', collections: ['weather'] },
  { symbol: '🌹', name: 'Red Rose', category: 'Animals & Nature', collections: ['love'] },
  { symbol: '🌺', name: 'Hibiscus', category: 'Animals & Nature' },
  { symbol: '🌻', name: 'Sunflower', category: 'Animals & Nature', collections: ['weather'] },
  { symbol: '🌼', name: 'Blossom Daisy', category: 'Animals & Nature' },
  { symbol: '🌷', name: 'Tulip', category: 'Animals & Nature' },
  { symbol: '🌱', name: 'Seedling Sprout', category: 'Animals & Nature' },
  { symbol: '🌿', name: 'Herb Leaf', category: 'Animals & Nature' },
  { symbol: '🍀', name: 'Four Leaf Clover', category: 'Animals & Nature' },

  // 4. Food & Drink
  { symbol: '🍇', name: 'Grapes', category: 'Food & Drink' },
  { symbol: '🍈', name: 'Melon', category: 'Food & Drink' },
  { symbol: '🍉', name: 'Watermelon', category: 'Food & Drink' },
  { symbol: '🍊', name: 'Tangerine Orange', category: 'Food & Drink' },
  { symbol: '🍋', name: 'Lemon', category: 'Food & Drink' },
  { symbol: '🍌', name: 'Banana', category: 'Food & Drink' },
  { symbol: '🍍', name: 'Pineapple', category: 'Food & Drink' },
  { symbol: '🥭', name: 'Mango', category: 'Food & Drink' },
  { symbol: '🍎', name: 'Red Apple', category: 'Food & Drink' },
  { symbol: '🍏', name: 'Green Apple', category: 'Food & Drink' },
  { symbol: '🍐', name: 'Pear', category: 'Food & Drink' },
  { symbol: '🍑', name: 'Peach', category: 'Food & Drink' },
  { symbol: '🍒', name: 'Cherries', category: 'Food & Drink' },
  { symbol: '🍓', name: 'Strawberry', category: 'Food & Drink' },
  { symbol: '🫐', name: 'Blueberries', category: 'Food & Drink' },
  { symbol: '🥝', name: 'Kiwi Fruit', category: 'Food & Drink' },
  { symbol: '🍅', name: 'Tomato', category: 'Food & Drink' },
  { symbol: '🥑', name: 'Avocado', category: 'Food & Drink' },
  { symbol: '🍆', name: 'Eggplant', category: 'Food & Drink' },
  { symbol: '🥔', name: 'Potato', category: 'Food & Drink' },
  { symbol: '🥕', name: 'Carrot', category: 'Food & Drink' },
  { symbol: '🌽', name: 'Ear of Corn', category: 'Food & Drink' },
  { symbol: '🍕', name: 'Pizza Slice', category: 'Food & Drink' },
  { symbol: '🍔', name: 'Hamburger', category: 'Food & Drink' },
  { symbol: '🍟', name: 'French Fries', category: 'Food & Drink' },
  { symbol: '🌭', name: 'Hot Dog', category: 'Food & Drink' },
  { symbol: '🍿', name: 'Popcorn', category: 'Food & Drink' },
  { symbol: '🥓', name: 'Bacon', category: 'Food & Drink' },
  { symbol: '🥚', name: 'Egg', category: 'Food & Drink' },
  { symbol: '🧇', name: 'Waffle', category: 'Food & Drink' },
  { symbol: '🥞', name: 'Pancakes', category: 'Food & Drink' },
  { symbol: '🍩', name: 'Doughnut', category: 'Food & Drink' },
  { symbol: '🍪', name: 'Cookie', category: 'Food & Drink' },
  { symbol: '🎂', name: 'Birthday Cake', category: 'Food & Drink', collections: ['celebration'] },
  { symbol: '🍰', name: 'Shortcake Slice', category: 'Food & Drink', collections: ['celebration'] },
  { symbol: '🧁', name: 'Cupcake', category: 'Food & Drink', collections: ['celebration'] },
  { symbol: '🥧', name: 'Pie', category: 'Food & Drink' },
  { symbol: '🍫', name: 'Chocolate Bar', category: 'Food & Drink' },
  { symbol: '🍬', name: 'Candy', category: 'Food & Drink' },
  { symbol: '🍭', name: 'Lollipop', category: 'Food & Drink' },
  { symbol: '☕', name: 'Hot Beverage Coffee', category: 'Food & Drink' },
  { symbol: '🧋', name: 'Bubble Tea Boba', category: 'Food & Drink' },
  { symbol: '🍶', name: 'Sake Bottle', category: 'Food & Drink' },
  { symbol: '🍾', name: 'Bottle with Popping Cork', category: 'Food & Drink', collections: ['celebration'] },
  { symbol: '🍷', name: 'Wine Glass', category: 'Food & Drink', collections: ['celebration'] },
  { symbol: '🍸', name: 'Cocktail Glass', category: 'Food & Drink' },

  // 5. Travel & Places
  { symbol: '🚗', name: 'Automobile Car', category: 'Travel & Places' },
  { symbol: '🚕', name: 'Taxi', category: 'Travel & Places' },
  { symbol: '🏎️', name: 'Racing Car', category: 'Travel & Places' },
  { symbol: '🚑', name: 'Ambulance', category: 'Travel & Places' },
  { symbol: '🚒', name: 'Fire Engine', category: 'Travel & Places' },
  { symbol: '✈️', name: 'Airplane Flight', category: 'Travel & Places' },
  { symbol: '🚀', name: 'Rocket Launch', category: 'Travel & Places', collections: ['fire'] },
  { symbol: '🛸', name: 'Flying Saucer UFO', category: 'Travel & Places', collections: ['stars'] },
  { symbol: '🪐', name: 'Ringed Planet Saturn', category: 'Travel & Places', collections: ['stars'] },
  { symbol: '🌌', name: 'Milky Way Galaxy', category: 'Travel & Places', collections: ['stars'] },
  { symbol: '🏖️', name: 'Beach with Umbrella', category: 'Travel & Places', collections: ['weather'] },
  { symbol: '⛰️', name: 'Mountain Peak', category: 'Travel & Places', collections: ['weather'] },
  { symbol: '🏰', name: 'Castle Manor', category: 'Travel & Places' },
  { symbol: '🗽', name: 'Statue of Liberty', category: 'Travel & Places' },
  { symbol: '🗼', name: 'Tokyo Tower', category: 'Travel & Places' },
  { symbol: '🏛️', name: 'Classical Building', category: 'Travel & Places' },

  // 6. Activities
  { symbol: '⚽', name: 'Soccer Football Ball', category: 'Activities' },
  { symbol: '🏀', name: 'Basketball', category: 'Activities' },
  { symbol: '🏈', name: 'American Football', category: 'Activities' },
  { symbol: '⚾', name: 'Baseball', category: 'Activities' },
  { symbol: '🥎', name: 'Softball', category: 'Activities' },
  { symbol: '🎾', name: 'Tennis Ball', category: 'Activities' },
  { symbol: '🏐', name: 'Volleyball', category: 'Activities' },
  { symbol: '🏉', name: 'Rugby Football', category: 'Activities' },
  { symbol: '🥏', name: 'Flying Disc Frisbee', category: 'Activities' },
  { symbol: '🎱', name: 'Eight Pool Ball', category: 'Activities', collections: ['gaming'] },
  { symbol: '🪀', name: 'Yo-Yo', category: 'Activities' },
  { symbol: '🏓', name: 'Ping Pong Table Tennis', category: 'Activities' },
  { symbol: '🏸', name: 'Badminton Racket', category: 'Activities' },
  { symbol: '🥊', name: 'Boxing Glove', category: 'Activities' },
  { symbol: '🎯', name: 'Direct Hit Bullseye', category: 'Activities', collections: ['gaming'] },
  { symbol: '🎮', name: 'Video Game Controller', category: 'Activities', collections: ['gaming'] },
  { symbol: '🕹️', name: 'Joystick Controller', category: 'Activities', collections: ['gaming'] },
  { symbol: '👾', name: 'Alien Monster Game Pixel', category: 'Activities', collections: ['gaming'] },
  { symbol: '🎲', name: 'Game Die Dice', category: 'Activities', collections: ['gaming'] },
  { symbol: '🎨', name: 'Artist Palette Painting', category: 'Activities' },
  { symbol: '🎤', name: 'Microphone Singing', category: 'Activities' },
  { symbol: '🎧', name: 'Headphones Music', category: 'Activities', collections: ['gaming'] },
  { symbol: '🎟️', name: 'Admission Tickets', category: 'Activities' },
  { symbol: '🔮', name: 'Crystal Ball Magic', category: 'Activities' },
  { symbol: '🏆', name: 'Trophy Victory', category: 'Activities', collections: ['gaming'] },
  { symbol: '🥇', name: 'First Place Gold Medal', category: 'Activities', collections: ['gaming'] },

  // 7. Objects
  { symbol: '💎', name: 'Diamond Gemstone', category: 'Objects' },
  { symbol: '💍', name: 'Diamond Ring', category: 'Objects', collections: ['love'] },
  { symbol: '🎁', name: 'Wrapped Gift Present', category: 'Objects', collections: ['celebration'] },
  { symbol: '📱', name: 'Mobile Smartphone', category: 'Objects' },
  { symbol: '💻', name: 'Laptop Computer', category: 'Objects' },
  { symbol: '💡', name: 'Light Bulb Idea', category: 'Objects' },
  { symbol: '🗝️', name: 'Old Vintage Key', category: 'Objects' },
  { symbol: '📜', name: 'Scroll Decree', category: 'Objects' },
  { symbol: '🛍️', name: 'Shopping Bags', category: 'Objects' },
  { symbol: '🎀', name: 'Ribbon Bow', category: 'Objects' },
  { symbol: '🎈', name: 'Party Balloon', category: 'Objects', collections: ['celebration'] },
  { symbol: '🎉', name: 'Party Popper', category: 'Objects', collections: ['celebration'] },
  { symbol: '🎊', name: 'Confetti Ball', category: 'Objects', collections: ['celebration'] },
  { symbol: '👑', name: 'Crown Royalty', category: 'Objects' },
  { symbol: '🕯️', name: 'Candle Light', category: 'Objects' },
  { symbol: '🪞', name: 'Mirror Glass', category: 'Objects' },
  { symbol: '📦', name: 'Package Box', category: 'Objects' },
  { symbol: '📫', name: 'Closed Mailbox', category: 'Objects' },
  { symbol: '✉️', name: 'Envelope Email', category: 'Objects' },
  { symbol: '💌', name: 'Love Letter Envelope', category: 'Objects', collections: ['love'] },

  // 8. Symbols
  { symbol: '❤️', name: 'Red Heart', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '🧡', name: 'Orange Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '💛', name: 'Yellow Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '💚', name: 'Green Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '💙', name: 'Blue Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '💜', name: 'Purple Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '🤎', name: 'Brown Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '🤍', name: 'White Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '🖤', name: 'Black Heart', category: 'Symbols', collections: ['hearts'] },
  { symbol: '💔', name: 'Broken Heart', category: 'Symbols', collections: ['sad', 'hearts'] },
  { symbol: '💕', name: 'Two Hearts', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💞', name: 'Revolving Hearts', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💓', name: 'Beating Heart', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💗', name: 'Growing Heart', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💖', name: 'Sparkling Heart', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💘', name: 'Heart with Arrow', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '💝', name: 'Heart with Ribbon', category: 'Symbols', collections: ['love', 'hearts'] },
  { symbol: '✨', name: 'Sparkles Stardust', category: 'Symbols', collections: ['stars', 'fire'] },
  { symbol: '⭐', name: 'Gold Star', category: 'Symbols', collections: ['stars'] },
  { symbol: '🌟', name: 'Glowing Star Burst', category: 'Symbols', collections: ['stars'] },
  { symbol: '💫', name: 'Dizzy Dizzy Star', category: 'Symbols', collections: ['stars'] },
  { symbol: '🔥', name: 'Fire Flame', category: 'Symbols', collections: ['fire'] },
  { symbol: '💥', name: 'Collision Blast Boom', category: 'Symbols', collections: ['fire'] },
  { symbol: '⚡', name: 'High Voltage Lightning Bolt', category: 'Symbols', collections: ['fire'] },
  { symbol: '💯', name: 'Hundred Points Score', category: 'Symbols', collections: ['fire'] },
  { symbol: '✔️', name: 'Check Mark Done', category: 'Symbols' },
  { symbol: '❌', name: 'Cross Mark Wrong', category: 'Symbols' },
  { symbol: '⛔', name: 'No Entry Access', category: 'Symbols' },

  // 9. Flags
  { symbol: '🇮🇩', name: 'Flag Indonesia', category: 'Flags' },
  { symbol: '🇯🇵', name: 'Flag Japan', category: 'Flags' },
  { symbol: '🇺🇸', name: 'Flag United States', category: 'Flags' },
  { symbol: '🇰🇷', name: 'Flag South Korea', category: 'Flags' },
  { symbol: '🇬🇧', name: 'Flag United Kingdom', category: 'Flags' },
  { symbol: '🏁', name: 'Chequered Flag Racing', category: 'Flags' },
  { symbol: '🚩', name: 'Triangular Red Flag', category: 'Flags' },
  { symbol: '🏳️‍🌈', name: 'Rainbow Flag', category: 'Flags' },
  { symbol: '🏴‍☠️', name: 'Pirate Jolly Roger Flag', category: 'Flags' },
];
