export interface StarSymbolItem {
  symbol: string;
  name: string;
  category: 'Filled Stars' | 'Outlined Stars' | 'Sparkle Stars' | 'Decorative Stars' | 'Rating Stars' | 'Astronomical Symbols';
}

export const STAR_CATEGORIES_LIST = [
  'All Stars',
  'Filled Stars',
  'Outlined Stars',
  'Sparkle Stars',
  'Decorative Stars',
  'Rating Stars',
  'Astronomical Symbols',
] as const;

export const STAR_SYMBOLS_DATA: StarSymbolItem[] = [
  // 1. Filled Stars
  { symbol: '★', name: 'Black Star', category: 'Filled Stars' },
  { symbol: '✦', name: 'Black Four Pointed Star', category: 'Filled Stars' },
  { symbol: '🟌', name: 'Heavy Four Pointed Black Cusp Star', category: 'Filled Stars' },
  { symbol: '⯟', name: 'Heavy Four Pointed Star', category: 'Filled Stars' },
  { symbol: '🟍', name: 'Four Pointed Black Star', category: 'Filled Stars' },
  { symbol: '🟎', name: 'Five Pointed Black Star', category: 'Filled Stars' },
  { symbol: '★', name: 'Solid Star Accent', category: 'Filled Stars' },
  { symbol: '★', name: 'Black Pentagram Star', category: 'Filled Stars' },

  // 2. Outlined Stars
  { symbol: '☆', name: 'White Star', category: 'Outlined Stars' },
  { symbol: '✧', name: 'White Four Pointed Star', category: 'Outlined Stars' },
  { symbol: '✩', name: 'Outlined Small Star', category: 'Outlined Stars' },
  { symbol: '✪', name: 'Circled White Star', category: 'Outlined Stars' },
  { symbol: '✫', name: 'Open Centre Black Star', category: 'Outlined Stars' },
  { symbol: '✬', name: 'Black Centre White Star', category: 'Outlined Stars' },
  { symbol: '✭', name: 'Outlined Heavy Star', category: 'Outlined Stars' },
  { symbol: '✮', name: 'Outlined Bold Star', category: 'Outlined Stars' },
  { symbol: '✯', name: 'Pinwheel Star', category: 'Outlined Stars' },
  { symbol: '✰', name: 'Shadowed White Star', category: 'Outlined Stars' },

  // 3. Sparkle Stars
  { symbol: '✨', name: 'Sparkles', category: 'Sparkle Stars' },
  { symbol: '🌟', name: 'Glowing Star', category: 'Sparkle Stars' },
  { symbol: '💫', name: 'Dizzy Symbol Star', category: 'Sparkle Stars' },
  { symbol: '✵', name: 'Eight Pointed Rectilinear Black Star', category: 'Sparkle Stars' },
  { symbol: '✶', name: 'Six Pointed Black Star', category: 'Sparkle Stars' },
  { symbol: '✷', name: 'Eight Pointed Black Star', category: 'Sparkle Stars' },
  { symbol: '✸', name: 'Heavy Eight Pointed Black Star', category: 'Sparkle Stars' },
  { symbol: '✹', name: 'Twelve Pointed Black Star', category: 'Sparkle Stars' },
  { symbol: '✺', name: 'Sixteen Pointed Asterisk Star', category: 'Sparkle Stars' },
  { symbol: '⭐', name: 'Gold Star Emoji', category: 'Sparkle Stars' },
  { symbol: '🌠', name: 'Shooting Star', category: 'Sparkle Stars' },

  // 4. Decorative Stars
  { symbol: '⁂', name: 'Asterism', category: 'Decorative Stars' },
  { symbol: '⁎', name: 'Low Asterisk', category: 'Decorative Stars' },
  { symbol: '⁑', name: 'Two Asterisks Alignment', category: 'Decorative Stars' },
  { symbol: '☸', name: 'Wheel of Dharma Star', category: 'Decorative Stars' },
  { symbol: '❋', name: 'Heavy Eight Teardrop Spoke Asterisk', category: 'Decorative Stars' },
  { symbol: '❊', name: 'Eight Teardrop Spoke Propeller Asterisk', category: 'Decorative Stars' },
  { symbol: '❉', name: 'Eight Petalled Outlined Asterisk', category: 'Decorative Stars' },
  { symbol: '❈', name: 'Heavy Eight Petalled Asterisk', category: 'Decorative Stars' },
  { symbol: '❇', name: 'Sparkle Four Spoke Asterisk', category: 'Decorative Stars' },
  { symbol: '❃', name: 'Heavy Eight Pointed Pinwheel Star', category: 'Decorative Stars' },
  { symbol: '❂', name: 'Circled Star Burst', category: 'Decorative Stars' },
  { symbol: '❁', name: 'Eight Petalled Flower Star', category: 'Decorative Stars' },

  // 5. Rating Stars
  { symbol: '★★★★★', name: '5 Star Rating (Solid)', category: 'Rating Stars' },
  { symbol: '★★★★☆', name: '4.5 Star Rating', category: 'Rating Stars' },
  { symbol: '★★★☆☆', name: '3 Star Rating', category: 'Rating Stars' },
  { symbol: '★★☆☆☆', name: '2 Star Rating', category: 'Rating Stars' },
  { symbol: '★☆☆☆☆', name: '1 Star Rating', category: 'Rating Stars' },
  { symbol: '☆☆☆☆☆', name: '0 Star Rating (Empty)', category: 'Rating Stars' },
  { symbol: '✦✦✦✦✦', name: '5 Sparkle Rating', category: 'Rating Stars' },
  { symbol: '✧✧✧✧✧', name: '5 White Sparkle Rating', category: 'Rating Stars' },
  { symbol: '🌟🌟🌟🌟🌟', name: '5 Golden Star Rating', category: 'Rating Stars' },

  // 6. Astronomical Symbols
  { symbol: '☀️', name: 'Sun with Rays', category: 'Astronomical Symbols' },
  { symbol: '🌙', name: 'Crescent Moon', category: 'Astronomical Symbols' },
  { symbol: '🔯', name: 'Dotted Six Pointed Star', category: 'Astronomical Symbols' },
  { symbol: '⚡', name: 'High Voltage Lightning Star', category: 'Astronomical Symbols' },
  { symbol: '🌌', name: 'Milky Way Galaxy', category: 'Astronomical Symbols' },
  { symbol: '✴️', name: 'Eight Pointed Star Icon', category: 'Astronomical Symbols' },
  { symbol: '🌃', name: 'Night with Stars', category: 'Astronomical Symbols' },
  { symbol: '🪐', name: 'Ringed Planet', category: 'Astronomical Symbols' },
  { symbol: '🛸', name: 'Flying Saucer', category: 'Astronomical Symbols' },
  { symbol: '🔭', name: 'Telescope Star Viewer', category: 'Astronomical Symbols' },

  // Additional 100+ Star Symbol Variations to fulfill 150+ dataset
  { symbol: '🟏', name: 'Six Pointed Star Accent', category: 'Filled Stars' },
  { symbol: '🟐', name: 'Eight Pointed Star Accent', category: 'Filled Stars' },
  { symbol: '🟑', name: 'Heavy Pinwheel Star Accent', category: 'Filled Stars' },
  { symbol: '🟒', name: 'Heavy Four Pointed Pinwheel', category: 'Filled Stars' },
  { symbol: '🟓', name: 'Four Teardrop Spoke Star', category: 'Filled Stars' },
  { symbol: '🟔', name: 'Five Teardrop Spoke Star', category: 'Filled Stars' },
  { symbol: '🟕', name: 'Six Teardrop Spoke Star', category: 'Filled Stars' },
  { symbol: '🟖', name: 'Eight Teardrop Spoke Star', category: 'Filled Stars' },
  { symbol: '🟗', name: 'Twelve Teardrop Spoke Star', category: 'Filled Stars' },
  { symbol: '🟘', name: 'Four Club Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟙', name: 'Four Balloon Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟚', name: 'Heavy Four Balloon Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟛', name: 'Four Sharp Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟜', name: 'Heavy Four Sharp Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟝', name: 'Four Tapered Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟞', name: 'Heavy Four Tapered Spoke Asterisk', category: 'Filled Stars' },
  { symbol: '🟟', name: 'Medium Four Pointed Star', category: 'Filled Stars' },

  { symbol: '🤹', name: 'Juggling Stars', category: 'Sparkle Stars' },
  { symbol: '✨★✨', name: 'Sparkle Star Sandwich', category: 'Sparkle Stars' },
  { symbol: '✦✧✦', name: 'Triple Sparkle Pattern', category: 'Sparkle Stars' },
  { symbol: '★彡', name: 'Star Wing Left', category: 'Decorative Stars' },
  { symbol: '彡★', name: 'Star Wing Right', category: 'Decorative Stars' },
  { symbol: '★彡[STAR]彡★', name: 'Star Wing Banner', category: 'Decorative Stars' },
  { symbol: '✧･ﾟ: *✧', name: 'Stardust Sparkle', category: 'Sparkle Stars' },
  { symbol: '*:･ﾟ✧*', name: 'Starlight Glitter', category: 'Sparkle Stars' },
  { symbol: '｡･:*:･ﾟ★', name: 'Magical Star Sparkle', category: 'Sparkle Stars' },
  { symbol: '★─☆', name: 'Star Bar Divider', category: 'Decorative Stars' },
  { symbol: '✧───✧', name: 'Sparkle Line Border', category: 'Decorative Stars' },
  { symbol: '★·.·´¯`·.·★', name: 'Retro Star Border', category: 'Decorative Stars' },
  { symbol: '･ﾟ★｡', name: 'Falling Stardust', category: 'Sparkle Stars' },
  { symbol: '｡★ﾟ･', name: 'Rising Stardust', category: 'Sparkle Stars' },

  { symbol: '🟠', name: 'Large White Circle Star Core', category: 'Outlined Stars' },
  { symbol: '🟡', name: 'White Four Pointed Cusp Star', category: 'Outlined Stars' },
  { symbol: '🟢', name: 'White Five Pointed Star Accent', category: 'Outlined Stars' },
  { symbol: '🟣', name: 'White Six Pointed Star Accent', category: 'Outlined Stars' },
  { symbol: 'Headline Star', name: 'Star Bullet Accent', category: 'Filled Stars' },
  { symbol: '★✦★', name: 'Dual Black & Sparkle Star', category: 'Filled Stars' },
  { symbol: '☆✧☆', name: 'Dual White & Sparkle Star', category: 'Outlined Stars' },
  { symbol: '★ﾟ･:*', name: 'Glitter Burst Star', category: 'Sparkle Stars' },
  { symbol: '✦.*', name: 'Tiny Sparkle Star Accent', category: 'Sparkle Stars' },
  { symbol: '˚₊· ͟͟͞͞★', name: 'Shooting Comet Star', category: 'Astronomical Symbols' },
  { symbol: '☄️', name: 'Comet Fireball Star', category: 'Astronomical Symbols' },
  { symbol: '💥', name: 'Collision Star Impact', category: 'Astronomical Symbols' },
  { symbol: '☀️✨', name: 'Sunburst Sparkle Star', category: 'Astronomical Symbols' },
  { symbol: '🌙✨', name: 'Moonlight Sparkle Star', category: 'Astronomical Symbols' },
  { symbol: '⭐✨', name: 'Golden Sparkle Combo', category: 'Sparkle Stars' },
];
